apiVersion: apps/v1
kind: Deployment
metadata:
  name: absensi-backend
  namespace: test-app
  labels:
    app: absensi-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: absensi-backend
  template:
    metadata:
      labels:
        app: absensi-backend
    spec:
      containers:
      - name: backend
        image: 192.168.100.58/devops-apps/backend:12
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: DB_HOST
          value: "192.168.100.70" # Atau nama service MySQL jika DB di dalam cluster
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: absensi-db-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: absensi-db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: absensi-db-secret
              key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: absensi-backend-service
  namespace: test-app
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.100.67
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: absensi-backend